ARG UBUNTU_DIST=noble
FROM ubuntu:noble

ARG UBUNTU_DIST
ARG ripgrep_VERSION
ARG BUILD_VERSION
ARG FULL_VERSION
ARG ARCH
ARG UV_RELEASE

RUN mkdir -p /output/usr/bin
RUN mkdir -p /output/usr/share/doc/ripgrep
RUN mkdir -p /output/DEBIAN

COPY ${UV_RELEASE}/* /output/usr/bin/
COPY output/DEBIAN/control /output/DEBIAN/
COPY output/DEBIAN/postinst /output/DEBIAN/postinst
RUN chmod 755 /output/DEBIAN/postinst
COPY output/copyright /output/usr/share/doc/ripgrep/
COPY output/changelog.Debian /output/usr/share/doc/ripgrep/
COPY output/README.md /output/usr/share/doc/ripgrep/

RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/usr/share/doc/ripgrep/changelog.Debian
RUN sed -i "s/FULL_VERSION/$FULL_VERSION/" /output/usr/share/doc/ripgrep/changelog.Debian
RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/DEBIAN/control
RUN sed -i "s/ripgrep_VERSION/$ripgrep_VERSION/" /output/DEBIAN/control
RUN sed -i "s/BUILD_VERSION/$BUILD_VERSION/" /output/DEBIAN/control
RUN sed -i "s/SUPPORTED_ARCHITECTURES/$ARCH/" /output/DEBIAN/control

RUN dpkg-deb --build /output /ripgrep_${FULL_VERSION}.deb
